# Generated by Django 2.0.8 on 2018-08-22 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='UUID')),
                ('name', models.CharField(default=None, help_text='[star_name] Stellar name most commonly used', max_length=120, verbose_name='Name')),
                ('name_hip', models.CharField(blank=True, help_text='[hip_name] Name of the star as given by the Hipparcos Catalog', max_length=120, null=True, verbose_name='HIP Name')),
                ('name_hd', models.CharField(blank=True, help_text='[hd_name] Name of the star as given by the Henry Draper Catalog', max_length=120, null=True, verbose_name='HD Name')),
                ('name_gj', models.CharField(blank=True, help_text='[gj_name] Name of the star as given by the Gliese Jahreiss Catalog', max_length=120, null=True, verbose_name='GJ Name')),
                ('name_tm', models.CharField(blank=True, help_text='[tm_name] 2MASS designation', max_length=120, null=True, verbose_name='TM Name')),
                ('is_exocat', models.BooleanField(default=False, help_text='[st_exocatflag] Flag indicating if a star is on the ExoCat Directing Imaging Mission star list', max_length=120, verbose_name='ExoCat List')),
                ('is_coronag', models.BooleanField(default=False, help_text='[st_coronagflag] Flag indicating if a star is on the Exo-C Coronagraph Probe star list', max_length=120, verbose_name='Exo-C Probe List')),
                ('is_starshade', models.BooleanField(default=False, help_text='[st_starshadeflag] Flag indicating if a star is on the Exo-S Starshade Probe star list', max_length=120, verbose_name='Exo-S Probe List')),
                ('is_wfirst', models.BooleanField(default=False, help_text='[st_wfirstflag] Flag indicating is a star is on the WFIRST coronagraph exoplanet list', max_length=120, verbose_name='WFIRST List')),
                ('is_lbti', models.BooleanField(default=False, help_text='[st_lbtiflag] Flag indicating if a star is on the LBTI survey list', max_length=120, verbose_name='LBTI List')),
                ('is_rv', models.BooleanField(default=False, help_text='[st_rvflag] Flag indicating if a star has RV data, either a detection or a non-detection', max_length=120, verbose_name='Known RV Data')),
                ('nb_planets', models.PositiveSmallIntegerField(default=0, help_text='[st_ppnum] Number of planets', verbose_name='Nb planets')),
                ('ra', models.CharField(blank=True, help_text='[rastr] Right Ascension in sexagesimal format.', max_length=48, null=True, verbose_name='Right ascension')),
                ('dec', models.CharField(blank=True, help_text='[decstr] Declination in sexagesimal notation', max_length=48, null=True, verbose_name='Declination')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='[st_dist] Distance to the planetary system in units of parsecs', max_digits=6, null=True, verbose_name='Distance')),
                ('distance_err_max', models.DecimalField(blank=True, decimal_places=2, help_text='[st_disterr1] in parsecs', max_digits=6, null=True, verbose_name='Distance maximum margin for error')),
                ('distance_err_min', models.DecimalField(blank=True, decimal_places=2, help_text='[st_disterr2] in parsecs', max_digits=6, null=True, verbose_name='Distance minimum margin for error')),
                ('vmag', models.DecimalField(blank=True, decimal_places=2, help_text='[st_vmag] Brightness as measured using the V band in units of magnitudes', max_digits=6, null=True, verbose_name='V-Band')),
                ('vmag_err', models.DecimalField(blank=True, decimal_places=2, help_text='[st_vmagerr]', max_digits=6, null=True, verbose_name='V-Band margin for error')),
                ('bmv', models.DecimalField(blank=True, decimal_places=2, help_text='[st_bmv] Color of the star as measured by the difference between B and V bands', max_digits=6, null=True, verbose_name='B-V')),
                ('bmv_err', models.DecimalField(blank=True, decimal_places=2, help_text='[st_bmverr]', max_digits=6, null=True, verbose_name='B-V margin for error')),
                ('stellar_type', models.CharField(default=None, help_text='[st_spttype] SClassification of the star based on their spectral characteristics following the Morgan-Keenan system', max_length=12, verbose_name='Stellar Spectral Type ')),
                ('luminosity_bolo', models.DecimalField(blank=True, decimal_places=2, help_text='[st_lbol] (log(solar)) Amount of energy emitted by a star per unit time, measured in units of solar luminosities. The bolometric corrections are derived from V-K or B-V colors', max_digits=6, null=True, verbose_name='Stellar Bolometric Luminosity')),
                ('luminosity_bolo_err', models.DecimalField(blank=True, decimal_places=2, help_text='[st_lbolerr]', max_digits=6, null=True, verbose_name='Stellar Bolometric Luminosity margin for error')),
            ],
        ),
    ]
